### ISSUE TITLE
Visualization checklist

### ISSUE THREAD

**Issue by hanpham32** [hanpham32/NetMotif#7]
- [ ] Make visualization an option for network > 1000 nodes
- [x] Display an interactive graph
- [ ] User can download and save graph
- [ ] Customize graph (colors, text, etc)
